import React, { useState, useEffect, useRef } from 'react';
import { useGame } from '../context/GameContext';
import ArrowLeftIcon from './icons/ArrowLeftIcon';
import BookOpenIcon from './icons/BookOpenIcon';
import MusicNoteIcon from './icons/MusicNoteIcon';
import BriefcaseIcon from './icons/BriefcaseIcon';
import FireIcon from './icons/FireIcon';
import ChartBarIcon from './icons/ChartBarIcon';
import StarIcon from './icons/StarIcon';

interface GuideSection {
    id: string;
    title: string;
    icon: React.ReactNode;
    content: React.ReactNode;
}

const guideSections: GuideSection[] = [
    {
        id: 'getting-started',
        title: 'Getting Started',
        icon: <BookOpenIcon className="w-5 h-5" />,
        content: (
            <>
                <p>Welcome to Red Mic! Your goal is to become a music superstar. You'll record songs, release projects, build a fanbase, and climb the charts. Success hinges on managing three key stats:</p>
                <ul className="list-disc list-inside space-y-2 pl-2">
                    <li><strong>Money:</strong> Your cash on hand. Used for everything from studio time to promotions. Earn it from streams, views, sales, and gigs.</li>
                    <li><strong>Popularity (0-100):</strong> A long-term measure of your fame. It grows with successful releases and decays slowly if you're inactive. Higher popularity leads to more organic streams, sales, and social media engagement.</li>
                    <li><strong>Hype (0-1000):</strong> A short-term measure of your buzz. Generated by new releases, promotional activities, and gigs. Hype decays every week. High hype provides a massive boost to streams for your entire catalog.</li>
                </ul>
            </>
        )
    },
    {
        id: 'music-studio',
        title: 'Studio & Releases',
        icon: <MusicNoteIcon className="w-5 h-5" />,
        content: (
            <>
                <p>The core of your career is making music. Go to the <strong>Studio</strong> app to record songs.</p>
                <ul className="list-disc list-inside space-y-2 pl-2">
                    <li><strong>Studio Selection:</strong> Better studios cost more but yield higher quality songs. Quality (0-100) directly impacts how well a song performs.</li>
                    <li><strong>Collaborations:</strong> You can pay for features from NPC artists. This boosts quality and initial hype.</li>
                    <li><strong>Releases:</strong> You can release Singles, EPs (3-7 songs), or Albums (8+ songs).</li>
                    <li><strong>Labels:</strong> Major labels take a cut and limit creative control, but provide massive promotional power and budget. Independent releases give you 100% earnings but less reach.</li>
                </ul>
            </>
        )
    },
    {
        id: 'charts',
        title: 'Climbing the Charts',
        icon: <ChartBarIcon className="w-5 h-5" />,
        content: (
            <>
                <p>Charts update every week. The <strong>Billboard Hot 100</strong> and <strong>Billboard 200</strong> are your ultimate goals.</p>
                <ul className="list-disc list-inside space-y-2 pl-2">
                    <li><strong>Streaming:</strong> The main driver for charts. High quality, hype, and popularity are key.</li>
                    <li><strong>Sales:</strong> Vinyl and CD sales from your Merch Store provide a massive boost to album chart positions.</li>
                    <li><strong>Certifications:</strong> Reach milestones to earn Gold, Platinum, and Diamond certifications for your songs and albums.</li>
                </ul>
            </>
        )
    },
    {
        id: 'social-media',
        title: 'Social Media & Hype',
        icon: <FireIcon className="w-5 h-5" />,
        content: (
            <>
                <p>Interact with fans and rivals on <strong>X</strong> (formerly Twitter) to build your presence.</p>
                <ul className="list-disc list-inside space-y-2 pl-2">
                    <li><strong>Posting:</strong> Share updates, photos, and videos. Fan accounts will react based on your popularity and recent activities.</li>
                    <li><strong>Fan Wars:</strong> You can choose to start rivalries with other artists. This generates massive hype but risks negative press and account suspension.</li>
                    <li><strong>Leaks:</strong> Unreleased songs can leak. This creates short-term buzz but removes "artificial" streams later. Security teams help prevent this.</li>
                </ul>
            </>
        )
    }
];

const GameGuideView: React.FC = () => {
    const { dispatch } = useGame();
    const [activeSection, setActiveSection] = useState(guideSections[0].id);
    const observer = useRef<IntersectionObserver | null>(null);

    useEffect(() => {
        observer.current = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    setActiveSection(entry.target.id);
                }
            });
        }, { threshold: 0.5 });

        guideSections.forEach(section => {
            const el = document.getElementById(section.id);
            if (el) observer.current?.observe(el);
        });

        return () => observer.current?.disconnect();
    }, []);

    const scrollTo = (id: string) => {
        const el = document.getElementById(id);
        if (el) el.scrollIntoView({ behavior: 'smooth' });
    };

    return (
        <div className="h-screen w-full bg-zinc-900 flex flex-col">
            <header className="p-4 flex items-center gap-4 sticky top-0 bg-zinc-900/80 backdrop-blur-sm z-10 border-b border-zinc-700/50">
                <button onClick={() => dispatch({type: 'CHANGE_VIEW', payload: 'game'})} className="p-2 rounded-full hover:bg-white/10">
                    <ArrowLeftIcon className="w-6 h-6" />
                </button>
                <h1 className="text-2xl font-bold">Game Guide</h1>
            </header>
            
            <div className="flex flex-grow overflow-hidden">
                <nav className="w-16 md:w-64 border-r border-zinc-800 p-2 space-y-2 overflow-y-auto">
                    {guideSections.map(section => (
                        <button 
                            key={section.id} 
                            onClick={() => scrollTo(section.id)}
                            className={`w-full flex items-center gap-3 p-3 rounded-lg transition-colors ${activeSection === section.id ? 'bg-red-600 text-white' : 'text-zinc-400 hover:bg-zinc-800'}`}
                        >
                            {section.icon}
                            <span className="hidden md:block font-semibold text-sm">{section.title}</span>
                        </button>
                    ))}
                </nav>
                
                <main className="flex-grow overflow-y-auto p-4 md:p-8 space-y-16 pb-32">
                    {guideSections.map(section => (
                        <section key={section.id} id={section.id} className="space-y-4 max-w-2xl mx-auto scroll-mt-24">
                            <div className="flex items-center gap-3 text-red-500">
                                {section.icon}
                                <h2 className="text-2xl font-bold">{section.title}</h2>
                            </div>
                            <div className="text-zinc-300 leading-relaxed space-y-4">
                                {section.content}
                            </div>
                        </section>
                    ))}
                </main>
            </div>
        </div>
    );
};

export default GameGuideView;
